# Generated by Django 5.2.1 on 2025-06-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], max_length=10)),
                ('message', models.TextField()),
                ('threshold_value', models.FloatField()),
                ('actual_value', models.FloatField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('response_time', 'Temps de réponse'), ('rag_accuracy', 'Précision RAG'), ('user_satisfaction', 'Satisfaction utilisateur'), ('message_delivery', 'Livraison message'), ('document_indexing', 'Indexation document')], max_length=30)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['metric_type', 'timestamp'], name='metrics_sys_metric__ddb202_idx')],
            },
        ),
    ]
