# Generated by Django 5.2.1 on 2025-06-21 17:04

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='ID de la tâche Celery pour le suivi', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='file',
            field=models.FileField(upload_to=documents.models.patient_document_path),
        ),
    ]
