# Generated by Django 5.2.1 on 2025-06-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentupload_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Pourcentage de progression du traitement (0-100)'),
        ),
    ]
