# Generated by Django 5.2.1 on 2025-06-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='n8n_workflow_id',
            field=models.CharField(blank=True, help_text='ID du workflow n8n associé', max_length=128, null=True),
        ),
    ]
