# Generated by Django 5.2.1 on 2025-06-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_n8n_workflow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='activation_link_clicked',
            field=models.BooleanField(default=False, help_text="Indique si le patient a cliqué sur le lien d'activation"),
        ),
    ]
